# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_id', models.IntegerField()),
                ('audio_external_link', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('handle', models.IntegerField()),
                ('is_private', models.IntegerField()),
                ('password', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('chat_title', models.TextField(max_length=150)),
                ('chat_body', models.TextField(max_length=550)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('quote_text', models.CharField(max_length=100)),
                ('quote_source', models.TextField(max_length=50)),
                ('link_url', models.CharField(max_length=250)),
                ('link_title', models.TextField(max_length=50)),
                ('link_caption', models.TextField(max_length=50)),
                ('post_status', models.CharField(choices=[('PUB', 'published'), ('DRA', 'draft'), ('SCH', 'scheduled'), ('PRE', 'preview')], default='DRA', max_length=20)),
                ('post_type', models.CharField(choices=[('TXT', 'text'), ('PIC', 'photo'), ('QUO', 'quote'), ('LINK', 'link'), ('AUD', 'audio'), ('VID', 'video')], default='PIC', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Audio')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Blogs')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Chats')),
                ('image_file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_id', models.IntegerField()),
                ('video_embed_code', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='video_file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Video'),
        ),
    ]
