# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
                ('caption', models.CharField(choices=[('GIF', 'gif'), ('JPG', 'jpeg'), ('PNG', 'png')], default='PNG', max_length=20)),
                ('image_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
